# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aedfc417347345a09cbeb5e1034dfa14189a1af0a2ab7b7ef906307121e876e0d8a14c4b39cae4ca55394628c51f9a2d8a8d1f0c7121961f5e062c8e00b1b4d2

test:
  secret_key_base: 5a2bd9a251aebf42983a019bc8475559e6cf85143aed7c107bc6e979f6029431b939733ffbd96f9d94f4cfdf80c812912243f598a5eb32795a474098170c3db7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
